### ISSUE TITLE
Author of a post can delete / edit their post

### ISSUE THREAD

**Issue by cosmicBboy** [the-sumit/sdsn-forum#107]

**Comment by JustWalters** [comment]
What's the best way to handle this and the hiding from #108?  I was thinking adding a marker in the schema that can identify a post as deleted/spam/hidden, but is there a better way?

**Comment by cosmicBboy** [comment]
@JustWalters I added this issue to [this milestone](https://trello.com/c/rTrfhT7Y/1-as-a-users-i-can-add-tags-to-my-posts-so-that-i-can-help-other-community-members-know-what-my-post-is-about) that I put on a trello card.

The idea is that deletions don't appear on the post list anymore, but Community Managers (Admins) can hide posts. The details on how to implement this are in the Requirements section on the Trello card.

Let me know if you have any questions
