### ISSUE TITLE
Footer not fixed when window is scrollable

### ISSUE THREAD

**Issue by JustWalters** [the-sumit/sdsn-forum#13]
When the viewport is smaller vertically and the scrollbar appears, the footer maintains its position relative to the top of the page, not the bottom.

**Comment by nshimiye** [comment]
would u mind specifying the branch used, and screen-shot if possible ?

**Comment by JustWalters** [comment]
This is on the current sumit-sdsn.meteor.com site. 

![image](https://cloud.githubusercontent.com/assets/4581439/6333234/6bc101f4-bb59-11e4-900b-ec7a6e2b5028.png)

The bottom window shows what I'm talking about.

**Comment by cosmicBboy** [comment]
fixed the footer problem. changed css on .footer from position: absolute to position: fixed. pulling changes to master now
