### ISSUE TITLE
fix user group filter

### ISSUE THREAD

**Issue by cosmicBboy** [the-sumit/sdsn-forum#21]
displays whole user list for a split second before filtering it

**Comment by nshimiye** [comment]
I'll check tomorrow

**Comment by cosmicBboy** [comment]
I think I fixed it. I added some data attributes to the [AdminController](https://github.com/the-sumit/sdsn-forum/blob/master/lib/controller.js), to provide the user data specific to a particular group.

This part fixed it: I commented out a section of the code in the [manage groups template](https://github.com/the-sumit/sdsn-forum/blob/dev/client/admin/manage-groups.js) which was pushing all the users into the each group before pushing the group-specific data.

The new data attribute data.groupUser in the Admin Controller now pulls the group-specific users only when the manage/:_id/users template is rendered.

Need to write some tests for this.

**Comment by nshimiye** [comment]
oh ok cool!


On Mon, Mar 9, 2015 at 2:29 PM, Niels Bantilan <notifications@github.com>
wrote:

> I think I fixed it. I added some data attributes to the AdminController
> <https://github.com/the-sumit/sdsn-forum/blob/master/lib/controller.js>,
> to provide the user data specific to a particular group.
>
> This part fixed it: I commented out a section of the code in the manage
> groups template
> <https://github.com/the-sumit/sdsn-forum/blob/dev/client/admin/manage-groups.js>
> which was pushing all the users into the each group before pushing the
> group-specific data.
>
> The new data attribute data.groupUser in the Admin Controller now pulls
> the group-specific users only when the manage/:_id/users template is
> rendered.
>
> Need to write some tests for this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/the-sumit/sdsn-forum/issues/21#issuecomment-77913595>.
>



-- 
Marcellin Nshimiyimana
Columbia University, SEAS
Computer Science-class of 2014
tel: +19319542053
