### ISSUE TITLE
create a Comments collection and model

### ISSUE THREAD

**Issue by cosmicBboy** [the-sumit/sdsn-forum#65]
data structure:

comment = {
    _id
    author: author._id,
    text: string or markdown, //markdown formats
    post: post._id
    parentComment: _id,
    childrenComment: [ _id ],
    timestamp: //make sure this is inserted into collection by default
    favoritedBy : [ _id ]
}

**Comment by JustWalters** [comment]
@cosmicBboy Am I supposed to be working on incorporating the comments package now?

**Comment by cosmicBboy** [comment]
yes, please check out [the comments-ui](https://atmospherejs.com/arkham/comments-ui) package and customize the package to use the data structure of the above schema. This will be the front-end implementation for rendering the comments associated with each post.

It uses the [simple-schema](https://github.com/aldeed/meteor-simple-schema) package to implement a data schema. The package we will use to implement comment inserts will be different, and will be another tast.

However, they both use simple-schema, so it will be worth it to define the Comment data model using simple schema. We will also have to refactor our other data models because it provides added methods and features for security.

**Comment by cosmicBboy** [comment]
For now, implement the out-of-the-box Comments-ui package, and have it attached to a particular post

**Comment by JustWalters** [comment]
The default schema uses different terminology (e.g. likes instead of favorites), and has a couple extra properties, but it has everything we need.
