### ISSUE TITLE
updating your meteor

### ISSUE THREAD

**Issue by nshimiye** [the-sumit/sdsn-forum#7]
Hi Niels, 
would you mind running the meteor update to get the newest version of the app.
This will prevent version based - merge conflicts 
thx!

**Comment by cosmicBboy** [comment]
Hey, which app? The sdsn-forum app is a fresh `meteor create`, so it' should be the latest version of everything

**Comment by nshimiye** [comment]
oh never mind, I found the problem
I got merge conflicts because I pulled instead of cloning lol

let me redo it.

Should we agree on the meteor version to use though ? what do you think

right this is the current version METEOR@1.0.3.1

**Comment by cosmicBboy** [comment]
yah, I think we should stick with METEOR@1.0.3.1
